### ISSUE TITLE
Address issues with MinIO implementation and backing storage location for object store

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/DMOD#242]
A specific, somewhat older version of the MinIO Docker image is being used (`minio/minio:RELEASE.2022-10-08T20-11-00Z`).  This was selected deliberately to work around an issue with the MinIO deployment in the `object_store` stack.

Currently, the stack is configured to use directories within a mounted filesystem as the backing storage location. 
 These directories are _/export1_ and _/export2_ for the standard deployment, or _/export_ for the single-node deployment.  The stack configuration expects external host directories to be bind-mounted into place for these (controlled via settings in the deployment-specific _.env_ file).

Starting shortly after the version used in the image above, MinIO removed the functionality that allowed this to work\* (it had already been deprecated).  DMOD needs to be updated to support other suitable mechanisms for providing a backing storage location. 

\* It should be confirmed whether the functionality is not available for single-node deployments of MinIO, but it is very possible this issue only relates to the multi-node deployment.

**Comment by aaraney** [comment]
> The stack configuration expects external host directories to be bind-mounted into place for these (controlled via settings in the deployment-specific .env file).


I am taking "external host directories" to mean something like an nfs drive? Can you clarify what you mean?

**Comment by robertbartel** [comment]
> I am taking "external host directories" to mean something like an nfs drive?

No, not necessarily.  Basically that just means the source of the "volumes," as controlled by `DMOD_OBJECT_STORE_HOST_DIR_1` and `DMOD_OBJECT_STORE_HOST_DIR_2` in the example below.  These have each typically been a path to a directory on the Docker host, in particular one on a local disk.

``` yaml
services:
  minio1:
    # TODO: temporary work around of backend storage mount (long term, this will need a different fix)
    image: minio/minio:RELEASE.2022-10-08T20-11-00Z
    hostname: minio1
    volumes:
      - ${DMOD_OBJECT_STORE_HOST_DIR_1:?No host data directory 1 for object store storage provided}:/export1
      - ${DMOD_OBJECT_STORE_HOST_DIR_2:?No host data directory 2 for object store storage provided}:/export2
      #- minio1-data3:/export3
      #- minio1-data4:/export4
      #- minio1-data5:/export5
      #- minio1-data6:/export6
```  

That said, I don't _think_ it really matters that the `/export1` and `/export2` directories inside the containers are backed by host bind mount volumes.  Rather, the problem (at least for high-availability MinIO deployments) is that they are directories.  MinIO seems to want/need to be backed by a device.
