### ISSUE TITLE
Refine docker network configuration

### ISSUE THREAD

**Issue by christophertubbs** [NOAA-OWP/DMOD#562]
The current process for deploying currently requires some complicated steps revolving around setting up networks. Things in docker are more streamlined now compared to when this project started, so some of the more complicated steps can be smoothed out. For example, the following in one of the deployment scripts can be pushed out to the docker-compose file:

```bash
    docker_dev_init_swarm_network ${DOCKER_REQUESTS_NET_NAME:=requests-net} \
            ${DOCKER_REQUESTS_NET_SUBNET:?Cannot init ${DOCKER_REQUESTS_NET_NAME} network without configured subnet} \
            ${DOCKER_REQUESTS_NET_GATEWAY:?Cannot init ${DOCKER_REQUESTS_NET_NAME} network without configured gateway} \
            ${DOCKER_REQUESTS_NET_DRIVER:-overlay}
```

to:

```yaml
network:
    requests-net:
        attachable: true
        ipam:
            driver: overlay
            config:
                subnet: ${DOCKER_REQUESTS_NET_SUBNET}
                gateway: ${DOCKER_REQUESTS_NET_GATEWAY}
```
(just an example - the 'real' solution would still need to be worked out)

The subnet and gateway definitions may no longer be needed. This change will cut down on some extra environment variables and scripts, making the project easier to maintain.
